# Generated by Django 3.2 on 2021-04-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyplanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
