# Generated by Django 3.2 on 2021-05-02 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyplanner', '0003_note_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='day',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
