# Generated by Django 3.2 on 2021-05-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyplanner', '0004_note_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
